### ISSUE TITLE
Update for Sublime Text 3

### ISSUE THREAD

**Issue by jklein** [bn0/nagios-sublime#2]
It would be great if this worked for ST3, which is hopefully going to be finished soon, and a lot of people are already using it.

**Comment by antonakv** [comment]
How is it going btw ?
I use Sublime 3 and plugin doesn't work :-(

**Comment by antonakv** [comment]
Please close issue. 
Tested in Sublime 3 build 3083. Works like a charm.

**Comment by jklein** [comment]
@antonakv can you update the README in that case? I'll close this.

**Comment by bn0** [comment]
I've removed references to the sublime text version from the project/readme, as it definitely works in ST2/3.
